{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kadinche.example",
    "module": "toastywrapper",
    "version": "0.0.1-debug",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "dg5iynmlvbfqbk6wogu2y6ez24"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "toastywrapper-0.0.1-debug.aar",
          "url": "toastywrapper-0.0.1-debug.aar",
          "size": 16368,
          "sha512": "a95f84f40e175f79363c5bc990e9363c104c12dfdd3bba5447f425743e7ccdc2f5af35dff0bd4859a9c0372877b1d18794145b5765508386d1647e14515c5617",
          "sha256": "5d05c91895604b41677753df81504c7fcce5aa2a1b1b98bb87466d41a40d39a0",
          "sha1": "42b8682650991cae0e0f47259c8c4b4c519737fa",
          "md5": "59addcd58d3e19271bdbf389b634d2e5"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.GrenderG",
          "module": "Toasty",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "toastywrapper-0.0.1-debug.aar",
          "url": "toastywrapper-0.0.1-debug.aar",
          "size": 16368,
          "sha512": "a95f84f40e175f79363c5bc990e9363c104c12dfdd3bba5447f425743e7ccdc2f5af35dff0bd4859a9c0372877b1d18794145b5765508386d1647e14515c5617",
          "sha256": "5d05c91895604b41677753df81504c7fcce5aa2a1b1b98bb87466d41a40d39a0",
          "sha1": "42b8682650991cae0e0f47259c8c4b4c519737fa",
          "md5": "59addcd58d3e19271bdbf389b634d2e5"
        }
      ]
    }
  ]
}
