{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kadinche.example",
    "module": "toastywrapper",
    "version": "0.0.1-debug",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "unl7pu6dhzbw3freya6xmoqtvm"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "toastywrapper-0.0.1-debug.aar",
          "url": "toastywrapper-0.0.1-debug.aar",
          "size": 16497,
          "sha512": "1eca69a436e808b519ee30422c97e929c0b45582b4ab2d30740b74bf1aa12a8248ce66b24b4a5ab66b1210354b81dca9903e29cab80ab7e4839def27a881fb70",
          "sha256": "c8a953e5a003a6151f396a603a8f090b00d9c3ef5947cbeb394ca2c84a607163",
          "sha1": "0d1c41c7d9c627e27676434a6a0b7edd24d10200",
          "md5": "f7d569a1e79e9aa724c6ce8e56a84632"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.GrenderG",
          "module": "Toasty",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "toastywrapper-0.0.1-debug.aar",
          "url": "toastywrapper-0.0.1-debug.aar",
          "size": 16497,
          "sha512": "1eca69a436e808b519ee30422c97e929c0b45582b4ab2d30740b74bf1aa12a8248ce66b24b4a5ab66b1210354b81dca9903e29cab80ab7e4839def27a881fb70",
          "sha256": "c8a953e5a003a6151f396a603a8f090b00d9c3ef5947cbeb394ca2c84a607163",
          "sha1": "0d1c41c7d9c627e27676434a6a0b7edd24d10200",
          "md5": "f7d569a1e79e9aa724c6ce8e56a84632"
        }
      ]
    }
  ]
}
