{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kadinche.example",
    "module": "toastywrapper",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "dg5iynmlvbfqbk6wogu2y6ez24"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "toastywrapper-0.0.1.aar",
          "url": "toastywrapper-0.0.1.aar",
          "size": 16126,
          "sha512": "f10a2cf2ab6487d9490810db5e7966c1a673ac69eb11aabf56610c8e0407f6d7f6c3048258bc5a56887e315b12575e0963f98db3ac5516dbcb95830fce57981e",
          "sha256": "d4570a441d45d100808aa61b701e6d9ca666310eeee55777c05bf55e72b797cc",
          "sha1": "2814698a59454d98146943df669466b820c30f0f",
          "md5": "3029a7b60fb37d8105bb8492795c9623"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.GrenderG",
          "module": "Toasty",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "toastywrapper-0.0.1.aar",
          "url": "toastywrapper-0.0.1.aar",
          "size": 16126,
          "sha512": "f10a2cf2ab6487d9490810db5e7966c1a673ac69eb11aabf56610c8e0407f6d7f6c3048258bc5a56887e315b12575e0963f98db3ac5516dbcb95830fce57981e",
          "sha256": "d4570a441d45d100808aa61b701e6d9ca666310eeee55777c05bf55e72b797cc",
          "sha1": "2814698a59454d98146943df669466b820c30f0f",
          "md5": "3029a7b60fb37d8105bb8492795c9623"
        }
      ]
    }
  ]
}
