{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kadinche.example",
    "module": "toastywrapper",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "unl7pu6dhzbw3freya6xmoqtvm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "toastywrapper-0.0.1.aar",
          "url": "toastywrapper-0.0.1.aar",
          "size": 16245,
          "sha512": "cc3b8c0e221c78cee625efa2b3d3ef3028bba11341762107a5983aa3387da1783b5e342bf4e48b97a6c26e18aa8b1d3e64f8362208eebf82239a267a3ea2eb6d",
          "sha256": "5c3582f9b56e4be7d36c2920ad16a7b2a55366358b0991b654c3cbe346251d1b",
          "sha1": "68b10af6fe52b30e794347b2c433714d3b9387c7",
          "md5": "4191ddc14f6b75dd8e003f4957fcf444"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.GrenderG",
          "module": "Toasty",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "toastywrapper-0.0.1.aar",
          "url": "toastywrapper-0.0.1.aar",
          "size": 16245,
          "sha512": "cc3b8c0e221c78cee625efa2b3d3ef3028bba11341762107a5983aa3387da1783b5e342bf4e48b97a6c26e18aa8b1d3e64f8362208eebf82239a267a3ea2eb6d",
          "sha256": "5c3582f9b56e4be7d36c2920ad16a7b2a55366358b0991b654c3cbe346251d1b",
          "sha1": "68b10af6fe52b30e794347b2c433714d3b9387c7",
          "md5": "4191ddc14f6b75dd8e003f4957fcf444"
        }
      ]
    }
  ]
}
